name: "Build"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  SQLX_OFFLINE: true

jobs:
  build_and_test:
    name: Build Rust Project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: Swatinem/rust-cache@v2

      - name: setup toolchain
        uses: hecrj/setup-rust-action@v2
        with:
          rust-version: stable

      - name: Cargo Test
        run: cargo test --all-features

      - name: Cargo Formatter
        run: cargo fmt --all -- --check

      - name: Cargo Clippy
        run: cargo clippy --all --all-features --tests -- -D warnings
